name: CI

on:
  push:
  pull_request:

jobs:
  python:
    name: Python checks (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install optional requirements (if present)
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Syntax check
        run: |
          python -m compileall -q \
            phase1-foundations/week1-python-cpp/day01-python-oop \
            phase1-foundations/week1-python-cpp/day02-numpy-scipy \
            phase1-foundations/week1-python-cpp/day03-threading \
            phase1-foundations/week2-math

      - name: Smoke tests
        run: |
          python phase1-foundations/week1-python-cpp/day01-python-oop/robot_state.py
          python phase1-foundations/week1-python-cpp/day02-numpy-scipy/trajectory.py
          python phase1-foundations/week1-python-cpp/day03-threading/sensors_threads.py

  cpp-linux:
    name: C++ build (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build Day 06 (CMake)
        run: |
          cmake -S "phase1-foundations/week1-python-cpp/day06-cmake-realtime" -B build
          cmake --build build --config Release
          ./build/threads_demo

      - name: Compile Day 04 (g++)
        run: |
          g++ -std=c++17 \
            phase1-foundations/week1-python-cpp/day04-cpp-oop/src/MotorDriver.cpp \
            phase1-foundations/week1-python-cpp/day04-cpp-oop/src/main.cpp \
            -I phase1-foundations/week1-python-cpp/day04-cpp-oop/src \
            -o day04_app
          ./day04_app

      - name: Compile Day 05 (g++)
        run: |
          g++ -std=c++17 \
            phase1-foundations/week1-python-cpp/day05-templates/src/main.cpp \
            -I phase1-foundations/week1-python-cpp/day05-templates/src \
            -o day05_app
          ./day05_app

  cpp-windows:
    name: C++ build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake - MSVC)
        run: cmake -S "phase1-foundations/week1-python-cpp/day06-cmake-realtime" -B build -G "Visual Studio 17 2022" -A x64

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Run binary
        shell: pwsh
        run: .\build\Release\threads_demo.exe
